### PR TITLE
Bracket multiplication

### LINKED ISSUE #22: Multiplication Improvement
This Calculation is mathematically correct:

`3(5-2)`

But FPC would only accept this:

`3x(5-2)`

### PR DESCRIPTION
**Pull request by not-nef**
Closes #22 

This took me over an hour to make, and its f***ing beautiful, i hope you like it

### CODE REVIEW

**Comment by im-coder-lg** [comment]
Bro no swearing!!! Lol

**Comment by not-nef** [comment]
Said who

**Comment by im-coder-lg** [comment]
Um... You? Look at the PR description version history bro, I censored it.

**Comment by im-coder-lg** [comment]
> Said who

> > Sarcasm: Said me! Check your PR description history!
> Read actuality!!!

# Actuality:
Check your PR description history, I edited it. It seems like there has to be some impulse control over cussing, well if here as a GitHub bot...

**Comment by HuyHung1408** [comment]
Wow, looks awesome. I'll accept it after I go back home

**Pull request merged**
